- airport: STN
  city: London
  country: United Kingdom
- airport: LGW
  city: London
  country: United Kingdom
- airport: DUB
  city: Dublin
  country: Ireland
- airport: BCN
  city: Barcelona
  country: Spain
- airport: MAD
  city: Madrid
  country: Spain
- airport: VLC
  city: Valencia
  country: Spain
- airport: LIS
  city: Lisbon
  country: Portugal
- airport: OPO
  city: Porto
  country: Portugal
- airport: FCO
  city: Rome
  country: Italy
- airport: CIA
  city: Rome
  country: Italy
- airport: MXP
  city: Milan
  country: Italy
- airport: BGY
  city: Bergamo
  country: Italy
- airport: NAP
  city: Naples
  country: Italy
- airport: BRU
  city: Brussels
  country: Belgium
- airport: CRL
  city: Charleroi
  country: Belgium
- airport: AMS
  city: Amsterdam
  country: Netherlands
- airport: BER
  city: Berlin
  country: Germany
- airport: VIE
  city: Vienna
  country: Austria
- airport: BSL
  city: Basel
  country: Switzerland
- airport: KRK
  city: Krakow
  country: Poland
- airport: BUD
  city: Budapest
  country: Hungary
- airport: PRG
  city: Prague
  country: Czechia
- airport: ZAG
  city: Zagreb
  country: Croatia
- airport: ATH
  city: Athens
  country: Greece
- airport: MLA
  city: Malta
  country: Malta
- airport: RAK
  city: Marrakech
  country: Morocco
- airport: TUN
  city: Tunis
  country: Tunisia
